### PR TITLE
create template and add a README

### PR DESCRIPTION
**Pull request by tobru**

### CODE REVIEW

**Comment by phil-pona** [comment]
nice one @dtschan can you please check?

**Comment by tobru** [comment]
README updated with hint for versioning and pushed first tag v1.0.0 for current master. I guess we can now merge #1 and #2 and create a new release v1.1.0?

**Comment by dtschan** [comment]
The https://github.com/appuio/letsencrypt repo already contains a template for installing the whole Let's Encrypt integration, including haproxy. I prefer not to duplicate resources. The template should either be merged with that one, or the letsencrypt.json template needs to be splitted and parametrized. Do you use the modified haproxy without the Let's Encrypt container?

**Comment by tobru** [comment]
Because we're treating the haproxy patch as it's own project in it's own repository I propose to have a template here to make this repository useable. It's not tied to our Let's Encrypt implementation, it could also be used for different implementations.
We should then update the template in the Let's Encrypt repository to integrate with this one.

**Comment by dtschan** [comment]
Thanks for the pull request. Please note that I'll have to make some changes to the template to make it compatible with our automation after the merge.

**Pull request merged**
